---
title: "RWorkSheet_Calopez#3b"
output: pdf_document
date: "2023-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = TRUE}

#1a

dfRespo <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
dfSex <- c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2)
dfFathersOccu <- c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1)
dfPerson_At_Home <- c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6)
dfSiblingsatSchool <- c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2)
dfTypesofHouses <- c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)

dfHouseholdData <- data.frame("Respondents" = dfRespo,
                              "Sex" = dfSex,
                              "Fathers Occupation" = dfFathersOccu,
                              "Persons at Home" = dfPerson_At_Home,
                              "Siblings at School" = dfSiblingsatSchool,
                              "Types of Houses" = dfTypesofHouses)
dfHouseholdData


#1b
#the data is about a Household occupants

summary(dfHouseholdData)

#c

#no, its 2.95

#d

#first_second <- dfHouseholdData[1:2,]
#first_second
first_second <- head(dfHouseholdData, 2)
first_second

#e
third5and2nd4 <- dfHouseholdData[c(3,5),c(2,4)]
third5and2nd4

#f
types_houses <- dfHouseholdData$Types.of.Houses
types_houses


#g

dfMaleFatherOccu <- dfHouseholdData[dfHouseholdData$Sex == 1 & dfHouseholdData$Fathers.Occupation == 1, c(2,3)]
dfMaleFatherOccu


#h

dfFemaleSiblings <- dfHouseholdData[dfHouseholdData$Sex == 2 & dfHouseholdData$Siblings.at.School >= 5, c(2,5) ]
dfFemaleSiblings




#2


dfofNum2 = data.frame(Ints=integer(),
                      Doubles=double(),
                      Characters=character(),
                      Logicals=logical(),
                      Factors=factor(),
                      stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(dfofNum2))

#it prints the structure of the dataframe

#3. Create a .csv file of this. Save it as HouseholdData.csv

newRespondent <- c(1:10)
newSex <- c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male")
newFathersOccupation <- c(1,2,3,3,1,2,2,3,1,3)
newPersonsAtHome <- c(5,7,3,8,6,4,4,2,11,6)
newSiblingsAtSchool <- c(2,3,0,5,2,3,1,2,6,2)
newTypesHouses <- c("Wood", "Congrete", "Congrete", "Wood", "Semi-congrete", "Semi-congrete", "Wood", "Semi-congrete", "Semi-congrete", "Congrete")

HouseholdData <- data.frame( 
  Respondents = newRespondent,
  Sex = newSex, 
  FatherOccupation = newFathersOccupation, 
  PersonsAtHome=newPersonsAtHome, 
  SiblingsAtSchool=newSiblingsAtSchool, 
  TypesOfHouses=newTypesHouses)
HouseholdData

write.csv(HouseholdData, file ="Household_Data.csv")

#a.Import the csv file into the R environment. Write the codes.
  
imported <- read.csv("Household_Data.csv")
imported

#b. Convert the Sex into factor using factor() function and change it into integer.[Legend: Male = 1 and Female = 2]. Write the R codes and its output.

imported$Sex <- factor(imported$Sex, levels = c("Male", "Female"))
imported$Sex<- as.integer(imported$Sex)
imported$Sex

# c. Convert the Type of Houses into factor and change it into integer. [Legend: Wood = 1; Congrete = 2; Semi-Congrete = 3]. Write the R codes and its output.

imported$HouseType <- factor(imported$TypesOfHouses, levels = c("Wood", "Congrete", "Semi-congrete"))
imported$HouseType <- as.integer(imported$HouseType)
imported$HouseType

#d.On father’s occupation, factor it as Farmer = 1; Driver = 2; and Others = 3. What is the R code and its output?

imported$FatherOccupation <- factor(imported$FatherOccupation, levels = c(1,2,3), labels = c("Farmer", "Driver", "Others"))
imported$FatherOccupation

# e. Select only all females respondent that has a father whose occupation is driver. Write the codes and its output.

femaleDriver <- imported[imported$Sex == 2 & imported$FatherOccupation == "Driver",]
femaleDriver

# f. Select the respondents that have greater than or equal to 5 number of siblings attending school. Write the codes and its output.
upper_five <- imported[imported$SiblingsAtSchool >= 5,]
upper_five 


#4
# The majority of the other sentiments on this day, July 14, are negative. This indicates that some subjects or occurrences generated negative attitude on that particular day.

# Even though all attitudes increased on this day, July 15, the negative sentiment is still at its greatest level. This suggests that something happened on that day that sparked unfavorable feelings.

# On these days, negative attitudes are still prevalent on July 17 and July 18, but neutral and positive sentiments are largely unchanged.

# On July 20, all sentiments reached their lowest points, although there were still more negative feelings among the others. This indicates that nothing happened on that day.

# All emotions are higher on this day, July 21, with the negative still dominating. This could imply that on that particular day, something happened that prompted people to react negatively.

#This information can lead us to the conclusion that public opinion is subject to outside influences and changes over time.


```