---
title: "RWorksheet#3a"
output: pdf_document
date: "2023-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r Let, echo = TRUE}

# 1. 
uppercase_letters <- LETTERS[1:26]
uppercase_letters

lowercase_letters <- letters[1:26]
lowercase_letters

# a. 
first_11 <- LETTERS [1:11]
first_11

# b. 
oddLetters <- LETTERS[c(TRUE, FALSE)]
oddLetters

# c. 
vowels <- LETTERS [c(1,5,9,15,21)]
vowels

# d.
five_lowercase <- letters [22:26]
five_lowercase

# e.
lowercase15_24 <- letters [15:24]
lowercase15_24



# 2.

# a.
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island","Davao City")
city

# b.
temp <- c(42,39,34,34,30,27)
temp

# c. 
data <- data.frame (temp = c(42,39,34,34,30,27),city = c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island","Davao City"))
data

# d. 
data2 <- data.frame (Temperature = temp, City = city)
data2


# e. 
matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[3, 2:3]

#f. 
matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[, 4]

#g. 
mat <- 2* matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
rownames(mat) <- c("isa", "dalawa", "tatlo")
colnames(mat) <- c("uno", "dos", "tres", "quatro")
mat


# h.
new_mat <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
dim(new_mat) <- c(6, 2)
new_mat


#3. 

#a.
data <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)

Array_Val <- array (c (1:3, 6:9, 0, 3:5, 1), c (2,4,3))
Array_Val

#b.
dim(Array_Val)

#c.

data <- c(1:3, 6:9, 0, 3:5, 1)
Array_Val <- array(data, dim = c(2, 4, 3))

dimnames(Array_Val) <- list(
  c("a", "b"),
  c("A", "B", "C", "D"),
  c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")
)

Array_Val
```
